language: java
script: mvn package
jdk:
- oraclejdk8
deploy:
  - provider: releases
    api_key:
      secure: Q4xKB2iQjQ9SZzouuiu4wV32sKkOSNd94yuOwWP+lpfBWLZJ8ttLs3fAMSBaLbamB697EueBoH+NmkPxMnoYQNJ6uVZJVZnweRfz59JHecFzdeJYsmUjokza6BIfXt19fKrkgCktVof7r7KwAtASjaGwAnuuDGydgw9kkdFx7nDcCLZZri5U/F7OfoCcAOSJ8SfF56vsafBXF8GD2cLjIAkmxMX4BPwDzALifv9J0+3nH7CQl4WptiRNP1bbyE8CZhxbLgvMBZP4ihsEfVqej3Yc0753rXMBRGfPa/kS1jqVAWGHXTTXpbMfpXDE/xxhnS+OvQxTSF8+n+DsKJqi6iOVFTNctqFszQyCNHfSxDeWRkVrOng2Sb+83FoyQt5PE4uQAWc4WoxBc0DPwxXAqQXPnOU1ucnT7alz6SGLvtv4/FspBe/2DhDHFXmVLByxEis7teYfLhH7XHonD1odOH43C69kOwRFTYnt5QzY/rx862gt2YS4bfUMfQ5+tdHzvoEMOF5GbO/QHBiIiik5m2mV9AwsEp/HCDCeSib6XdjYGmBd7F2CPS8ZAzuxScX1LV3uJDNg9KgI5AhI6CHxygrPNDT/6s3prcIm9x7dl8L2QQAIjmlJvEL0o1Dwn1+JV867ssYZUJ6rYr3R2MhWHzP2AJkOdUG0ZFWbcyi6y7c=
    file: target/*.jar
    on:
      repo: paslavsky/mockito-kt
      branch: v.1.0.0
  - provider: bintray
    file: descriptor.json
    user: paslavsky
    key:
      secure: dVFoLWkEpa+Gr6eMDHV4dDEdX5I3xOZBE3CjgNTVYEsc1h6friMcvFfXlA3ofpzZT1I+sHphEGH/vwxYv2Fb2R6mFW+wZckUxu81fAN6NKivbCtdeYMJpbARdVb7AI8lQp6zrNq0x9b2PscDetxkpiRCEyrHNGb1Y/IFYF/x6wfn++eG58MiOKnYTYQZrA2tPVl8Pqj89QC3wpcnpl1Z6P7Ch4LAjL1FlJY01/bia/1Zycm7oTI4+xrlvUK/F4PdMmF7/31jSgzoQuS4E9p6FVDcMZHNTCzJq4jR7stJvgPYWvvE3Pwx0Ac9cd7/ChI4HSIJHFLUkfKeUrULxamEdzlpSrmSL1RPcaCH9LTXWrozbDD+HcmqxR8SiK4v/oR49O6SX+IdepSLOMV9XlNdpQ8NImsNmdrfA4MyFSgnqfC3IZFnQxeWuqwIM9ZJOy6x8pP04UzVyqYMTWm7S7NYv+q0zgO8l6hYfKZPW0Dt7nUTZfp7/5IwHOsvrn41eLPJ7q5FYlUqMMZKeXrvb9PtmkICivVVSmx8C7i4DIPzLmbMeFyx5ifVDn8rL/pRN12NFb3z2dv9OcBiijfUkWLtXAPxbFEEMtEHQiEFoo0dv5j7IDoFaWd9tyaE+0yHljsk7cdKFul+ZQX+J4KkCGgQnkrBNEG0U086iLZQCSbVhcQ=
    on:
      repo: paslavsky/mockito-kt
      branch: v.1.0.0
    dry-run: true