language: java
script: mvn package
jdk:
  - oraclejdk8
deploy:
  - provider: releases
    api_key:
      secure: GA/ki1ihVEOon4FojijA+P/EQSBphDxDH6AgPaD3LDYy6KTjwYLVMPxeF0LxrH16DtYnhlktTungrUuxFRMQE9hL9pZzqf/zVFRvkBLp2nqw3u/cXy1dwpolbarmQg00zobEmBu3CAmUCDqeK7szDeQMfNQQ6h5HpmBoqJ9XPfJouVxmxW5iFxXLGytTIAwH6dDj72gtCju42q9vTMBz8XGxRc6FfdHXUcwgv/iR5ul27k6kn6/v8717s/lOiS4YBA9/hiQzq8KU/JvVq2gxc+v0IWZUJ0VK9YOjcocv63vxvBvcWEglQldtEC7bcFrXFHclhYkFfyieCbGmRQiYv19L3YStUPnjOg+swzvQ5MsfyDeXZlOusySvx5DDXNBF46nIuixs+LHXTsDrx545jr1lZ9Feq7HcvJCelQ4HGHP3zCNY93vcQXTTKePGrvytjvUO6mBqxyVrnrWVAmqqfgqaTgg3kAEWbP6XrC0XAx7RtNtwkhueBYuG9pC5uVAG+ZKCO/TjsWDsl09sHgTdBEBRMd9aaTTWrueUp8bFuk2U+YgreZhT1KUM9x6OTlC5aiEMgBnm//C5djGuee9dypEIVTCl6j81wsFjnly09/f9MGraWWLFnW4QkLFsxIVRAbhtC255Cul7p5j1AU5A/jeGclqH5qQfeX9EayTU23k=
    file: "./target/mockito-kt*.jar"
    skip_cleanup: true
    file_glob: true
    overwrite: true
    on:
      repo: paslavsky/mockito-kt
      branch: master
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    skip_cleanup: true
    on:
      repo: paslavsky/mockito-kt
      branch: master